devtools::install_github("christophe-stevens/EnsembleBaseClass")
devtools::install_github("christophe-stevens/EnsemblePCClass")

require("EnsembleBaseClass") 
require("EnsemblePCClass") 


####################################
#
# chris-test : 
#
####################################
# Required package for benchmarking dataset
require(mlbench)  # install.packages("mlbench")  

# require ML BENCH
data(PimaIndiansDiabetes)
# Data preparation
dataset <- PimaIndiansDiabetes
dataset$diabetes <- as.numeric(ifelse(dataset$diabetes=="pos",1,0))
myformula <- diabetes ~ insulin + age + triceps
perc.train <- 0.7
index.train <- sample(1:nrow(dataset), size = round(perc.train*nrow(dataset)))
data.train <- dataset[index.train,]
data.predict <- dataset[-index.train,]


control <- epcclass.baselearner.control(baselearners=c("svm","xgboost","rf",
                                                       "penreg","nnet","knn",
                                                       "bart"))
ensemble <- epcclass(formula =  myformula, data = data.train, 
                     baselearner.control= control, ncores=8)
plot(ensemble)
newpred <- predict(ensemble,newdata=data.predict)
mean((newpred-data.predict$diabetes)^2)
table(round(newpred), data.predict$diabetes)
